name: Auto Release

on:
  push:
    tags:
      - "*"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Check tag is on main
        run: |
          git fetch origin main
          git branch -r --contains $GITHUB_SHA | grep origin/main

      - name: Check ZIP
        run: |
          echo "Current commit:"
          git rev-parse HEAD

          echo "Tag commit:"
          git rev-list -n 1 $GITHUB_REF_NAME

          echo "ZIP info:"
          ls -lh release/DiskInfo.zip
          md5sum release/DiskInfo.zip
    
      - name: Validate tag
        run: |
          echo "$GITHUB_REF_NAME" | grep -Ei "[0-9]"

      - name: Extract changelog
        id: changelog
        run: |
          awk '/^## DiskInfo version '"${GITHUB_REF_NAME}"'/{flag=1;next}/^---/{flag=0}flag' CHANGELOG.md > RELEASE_NOTES.txt

          echo "notes<<EOF" >> $GITHUB_OUTPUT
          cat RELEASE_NOTES.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
    
      - name: Create Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          name: DiskInfo version ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.notes }}
          files: |
            release/DiskInfo.zip