name: Auto Release

on:
	push:
		tags:
			- "*"

jobs:
	release:
		runs-on: ubuntu-latest

		steps:
			- name: Checkout
				uses: actions/checkout@v4

			- name: Create Release
				uses: softprops/action-gh-release@v2
				with:
					body: "Please read CHANGELOG.md for changes."
					files: |
						release/DiskInfo.zip
				env:
					GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}