name: Auto Release

on:
  push:
    tags:
      - "*"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

- name: Extract changelog
  id: changelog
  run: |
    awk '/^## DiskInfo version '"${GITHUB_REF_NAME}"'/{flag=1;next}/^---/{flag=0}flag' CHANGELOG.md > RELEASE_NOTES.txt

    echo "notes<<EOF" >> $GITHUB_OUTPUT
    cat RELEASE_NOTES.txt >> $GITHUB_OUTPUT
    echo "EOF" >> $GITHUB_OUTPUT
    
      - name: Create Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          name: DiskInfo version ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.notes }}
          files: |
            release/DiskInfo.zip