name: Update Winget

on:
  push:
    tags:
      - "*"

jobs:
  winget:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: taiki-e/install-action@v2
        with:
          tool: komac

      - name: Submit manifest
        env:
          GITHUB_TOKEN: ${{ secrets.WINGET_TOKEN }}
        run: |
          TAG="${GITHUB_REF_NAME}"

          URL="https://github.com/${{ github.repository }}/releases/download/$TAG/DiskInfo.zip"

          komac update \
            --identifier HoangLong.DiskInfo \
            --version "$TAG" \
            --urls "$URL" \
            --submit