name: Update Winget

on:
  release:
    types:
      - published

jobs:
  winget:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install WingetCreate
        shell: pwsh
        run: |
          Invoke-WebRequest `
            https://aka.ms/wingetcreate/latest `
            -OutFile wingetcreate.exe

      - name: Submit manifest
        env:
          WINGETCREATE_GITHUB_TOKEN: ${{ secrets.WINGET_TOKEN }}
        shell: pwsh
        run: |
          $Tag = "${{ github.event.release.tag_name }}"
          $Url = "https://github.com/${{ github.repository }}/releases/download/$Tag/DiskInfo.zip"

          .\wingetcreate.exe update HoangLong.DiskInfo `
            --version $Tag `
            --urls $Url `
            --release-note-url https://github.com/Hoang-Long2012/DiskInfo/blob/main/CHANGELOG.md `
            --submit